spring.jackson.serialization.INDENT_OUTPUT: true
management:
    server:
        port: 8090
    endpoints:
        prometheus:
            enabled: true
        metrics:
            enabled: true
        web:
            exposure:
                include: "*"
    metrics:
        export:
            prometheus:
                enabled: true
geoIP:
    enabled: false
    url: https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
source:
    epg:
        refresh: 600
    channels:
        refresh: 60
    reconnectTimeout: 15
userAgent: proxyLive
streamTimeout: 30
ffmpeg:
    path: ffmpeg
    profiles:
        -
            alias: "aac"
            parameters: "-i {input} {channelParameters} -sn -ac 2 -c:a libfdk_aac -b:a 320k -c:v copy"
        -
            alias: "360p"
            parameters: "-i {input} {channelParameters} -sn -c:a:0 libfdk_aac -ac 2 -b:a 96k -c:v libx264 -tune zerolatency -g 10 -vprofile high -level 4.0 -crf 18 -movflags +faststart -bufsize 15000k -maxrate 700k  -preset veryslow -vf scale=-1:360,yadif=0"
        -
            alias: "480p"
            parameters: "-i {input} {channelParameters} -sn -c:a:0 libfdk_aac -ac 2 -b:a 196k -c:v libx264 -tune zerolatency -g 10 -vprofile high -level 4.0 -crf 18 -movflags +faststart -bufsize 15000k -maxrate 1500k  -preset slow -vf scale=-1:484,yadif=0"
        -
            alias: "720p"
            parameters: "-i {input} {channelParameters} -sn  -c:a:0 libfdk_aac -ac 2 -b:a 320k -c:v libx264 -tune zerolatency -g 10 -vprofile high -level 4.0 -crf 18 -movflags +faststart -bufsize 15000k -maxrate 3000k  -preset fast -vf scale=-1:720,yadif=0"
        -
            alias: "1080p"
            parameters:  "-i {input} {channelParameters} -sn  -c:a:0 libfdk_aac -ac 2 -b:a 320k -c:v libx264 -tune zerolatency -g 300 -vprofile high -level 4.0 -movflags +faststart -bufsize 15000k -maxrate 5000k  -preset faster -vf yadif=0"
        -
            alias: "vaapi1080p"
            parameters: "-hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i {input} {channelParameters} -sn  -c:a:0 aac -ac 2 -b:a 320k -c:v h264_vaapi -tune zerolatency -g 300 -level 41 -movflags +faststart -bufsize 15000k -maxrate 5000k  -preset faster -vf format=vaapi,hwupload,deinterlace_vaapi"
    mpegTS:
        parameters: "-threads 0 -f mpegts -mpegts_copyts 1 -mpegts_flags +resend_headers  -nostats -hide_banner"
    hls:
        tempPath: "/tmp"
        parameters: "-flags -global_header  -avoid_negative_ts disabled -map_metadata -1 -start_at_zero -copyts -flags -global_header -vsync cfr -y -nostats -hide_banner -f hls  -hls_time 2 -hls_list_size 10  -hls_flags delete_segments  -hls_flags +append_list -hls_flags +discont_start -hls_flags +delete_segments"
        timeout: 30

buffers:
    chunkSize: 131072
    broadcastBufferSize: 52428800

authentication:
    expireInHours: 48