FROM jrottenberg/ffmpeg:2.4.3
MAINTAINER Isaac Aymerich <isaac.aymerich@gmail.com>

ENV	LANG en_US.UTF-8
ENV	LC_ALL en_US.UTF-8

RUN yum install -y curl; yum upgrade -y; yum update -y;  yum clean all

ENV JDK_VERSION 8u31
ENV JDK_BUILD_VERSION b13

RUN curl -LO "http://download.oracle.com/otn-pub/java/jdk/$JDK_VERSION-$JDK_BUILD_VERSION/jdk-$JDK_VERSION-linux-x64.rpm" -H 'Cookie: oraclelicense=accept-securebackup-cookie' && rpm -i jdk-$JDK_VERSION-linux-x64.rpm; rm -f jdk-$JDK_VERSION-linux-x64.rpm; yum clean all

ENV JAVA_HOME /usr/java/default

ENTRYPOINT ["java", "-jar", "/usr/local/vod-transcoder/vod-transcoder.jar"]